=== seek4science/seek/lib/seek/extended_metadata_type/emt_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "supported_type": {
      "type": "string"
    },
    "enabled": {
      "type": "boolean"
    },
    "attributes": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "label": {
              "type": "string"
            },
            "description": {
              "type": "null"
            },
            "type": {
              "type": "string"
            },
            "required": {
              "type": "boolean"
            }
          },
          "required": [
            "title",
            "label",
            "description",
            "type",
            "required"
          ]
        },
        {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "label": {
              "type": "string"
            },
            "description": {
              "type": "null"
            },
            "type": {
              "type": "string"
            },
            "required": {
              "type": "boolean"
            }
          },
          "required": [
            "title",
            "label",
            "description",
            "type",
            "required"
          ]
        }
      ]
    }
  },
  "required": [
    "title",
    "supported_type",
    "enabled",
    "attributes"
  ]
}

=== seek4science/seek/test/fixtures/files/extended_metadata_type/valid_emt_with_cv_with_ontologies.json
{
  "title": "An example with attributes associated with ontology terms",
  "supported_type": "Study",
  "enabled": true,
  "attributes": [
    {
      "title": "Topics",
      "description": "Topics, used for annotating. Describes the domain, field of interest, of study, application, work, data, or technology. Initially seeded from the EDAM ontology.",
      "type": "Controlled Vocabulary",
      "required": true,
      "pos": 1,
      "ID": "CV_TOPICS_ID"
    }
  ]
}

=== seek4science/seek/test/fixtures/files/extended_metadata_type/valid_emt_with_linked_emt.json
{
  "title": "family",
  "supported_type": "Investigation",
  "enabled": true,
  "attributes": [
    {
      "title": "dad",
      "label": "Dad",
      "description": null,
      "type": "Linked Extended Metadata",
      "required": false,
      "pid": "https://somevocab.org/father",
      "ID": "PERSON_EMT_ID"
    },
    {
      "title": "mom",
      "label": "Mom",
      "description": null,
      "type": "Linked Extended Metadata",
      "required": false,
      "ID": "PERSON_EMT_ID"
    },
    {
      "title": "child",
      "label": "child",
      "description": null,
      "type": "Linked Extended Metadata (multiple)",
      "required": false,
      "ID": "PERSON_EMT_ID"
    }
  ]
}

=== seek4science/seek/test/fixtures/files/extended_metadata_type/valid_simple_emt.json
{
  "title": "person",
  "supported_type": "ExtendedMetadata",
  "enabled": true,
  "attributes": [
    {
      "title": "first_name",
      "type": "String",
      "required": true
    },
    {
      "title": "last_name",
      "label": "last name",
      "description": null,
      "type": "String",
      "pid": "http://schema.org/family_name"
    }
  ]
}

=== seek4science/seek/test/fixtures/files/extended_metadata_type/valid_emt.json
{
  "title": "person",
  "supported_type": "ExtendedMetadata",
  "enabled": true,
  "attributes": [
    {
      "title": "first_name",
      "type": "String"
    },
    {
      "title": "last_name",
      "label": "Last name",
      "description": null,
      "type": "String",
      "required": false
    }
  ]
}
